### ISSUE TITLE
Notation for parameterized function type

### ISSUE THREAD

**Issue by jeltsch** [tweag/ghc#10]
In some articles on the linear types extension, a certain notation for applying a generic function type constructor to a multiplicity constraint is used. This notation is `->_m` where `m` is either `1` or `ω`. (Apparently, this notation has not been implemented in the prototype, though.)

I think that this notation is not a good idea. It resembles the LaTeX notation for arrows with subscripts (like →₁), but it is completely different from what is usual in Haskell. Haskell has two ways of denoting application of a type or value to an argument: one is ordinary prefix application (like in `(->) Int String`); the other one is infix application (like in `Int -> String`). Adding another notation for application makes things confusing and may cause all kinds of syntactic awkwardness.

Furthermore, it does not seem right to me to use the arrow `->` to denote the generic function type constructor (the one that covers both the linear and the non-linear case), since it already refers specifically to the non-linear function type constructor.

I propose to add a new identifier that denotes the generic function type constructor and use ordinary prefix application for it. An interface could look as follows:

```
data MultiplicityConstraint = ExactlyOnce | ArbitrarilyOften

type Function :: MultiplicityConstraint -> * -> * -> * -- hard-coded

type (-+) = Function ExactlyOnce
type (->) = Function ArbitrarilyOften
```

The identifiers `ExactlyOnce` and `ArbitrarilyOften` could generally be used instead of `1` and `ω` (for example, also in error messages), resolving #9.

**Comment by aspiwack** [comment]
It might be the right way to go: it's conceptually simple. But we have to consider the multiplicity-polymorphic extension, in which we do expect functions to be written using explicit multiplicities.

Something like (borrowing syntax from Edsko de Vries) : `forall (p::Multiplicity), (a ->:p b) -> [a] ->:p b`. Not having an infix notation for `->:p`, in the above would be plainly horrendous. So some compromise has to be made here.

**Comment by aspiwack** [comment]
Closing: the discussion should now move to ghc-proposals/ghc-proposals#91.
