### ISSUE TITLE
Add back cheap test in `pushCoDataCon`

### ISSUE THREAD

**Issue by mpickering** [tweag/ghc#100]
At one point I commented out the fast branch of the `CoreOpt.pushCoDataCon` function because it was causing a lot of problems with multiplicity arguments. The slow branch seems to work fine so I left it commented out but it really should be reenabled.

**Comment by aspiwack** [comment]
GHC seems to compile with the fast path on. But it seem to produce verbose warnings. I'm running a CI to analyse.

**Comment by aspiwack** [comment]
This was just due to debugging trace that I had fail to remove.
