### ISSUE TITLE
Reenable the checkCoercionHole assertion

### ISSUE THREAD

**Issue by mpickering** [tweag/ghc#106]
In da6f77b2deeac9234f69bf416c9b2dcb925ff9f5 I disabled the `checkCoercionHole` assertion which was failing for `Data.ByteString.Builder.Internal`. It needs to be reenabled and debugged if it is still failing but it is the kind of failure which is hard to find the cause of and likely to be fixed by other bug fixes.

**Comment by aspiwack** [comment]
Done in 4cc4649efc2812f416a27dd8b3ec3ee04b5ad281.
