### ISSUE TITLE
Spurious multiplicity error resulting from undefined variable

### ISSUE THREAD

**Issue by rrnewton** [tweag/ghc#118]
This is one of those many little issues on error-reporting, but I think this one is clear cut at least.

If we have a linear function application `foo bar`, let's say we forget to import `foo`.  We get two error messages reported, in this order:

```
    • Couldn't match expected weight ‘1’ of variable ‘bar’ with actual weight ‘ω’
    • In an equation for ‘...’:   ... = ... (foo bar) ...
...
    • Variable not in scope: foo :: A -> B
```

Well, here the multiplicity error is kind of spurious.  It's not that bar *wasn't* used, it was just used as operand to a function that happens to be undefined!  

If both these errors are generated (and it would be better to suppress the weight error), then at least it would be nice if the "not in scope" could go first.  But if errors are always in the strict order of source location, then of course that would not be possible...

**Comment by monoidal** [comment]
This no longer occurs. I'm not sure when it was fixed though.
