### ISSUE TITLE
Type families being expanded late can cause inferrence issues

### ISSUE THREAD

**Issue by Tarmean** [tweag/ghc#12]
I stumbled upon a curious situation while playing around with GADTs. In short, changing an `a ⊸ b` annotation to `Arr 'One a b` causes some code to stop compiling. Simplified example:

```
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE TypeFamilyDependencies #-}
module LMonad where

apply :: forall p a b . UnrestrictedIf p a ⊸ Arr p a b ⊸ b
apply (Linear a) = \f -> (f :: a ⊸ b) a
apply (NotLinear a) = \f -> f a

data Multiplicity = One | Omega

type family Arr (p :: Multiplicity) a b = result | result -> a b where
    Arr 'One a b = a ⊸ b
    Arr 'Omega a b = a -> b

data UnrestrictedIf p a where
    Linear :: a ⊸ UnrestrictedIf 'One a
    NotLinear :: a -> UnrestrictedIf 'Omega a
```
When changing the annotation in apply to `Arr 'One a b`:

```
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE TypeFamilyDependencies #-}
module LMonad where

apply :: forall p a b . UnrestrictedIf p a ⊸ Arr p a b ⊸ b
apply (Linear a) = \f -> (f :: Arr 'One a b) a
apply (NotLinear a) = \f -> f a

data Multiplicity = One | Omega

type family Arr (p :: Multiplicity) a b = result | result -> a b where
    Arr 'One a b = a ⊸ b
    Arr 'Omega a b = a -> b

data UnrestrictedIf p a where
    Linear :: a ⊸ UnrestrictedIf 'One a
    NotLinear :: a -> UnrestrictedIf 'Omega a
```

ghc gives the following error:

```
LMonad.hs:46:15: error:
    • Couldn't match expected weight ‘1’ of variable ‘a’ with actual weight ‘ω’
    • In the pattern: Linear a
      In an equation for ‘apply’:
          apply (Linear a) = \ f -> (f :: Arr  'One a b) a
   |
46 | apply (Linear a) = \f -> (f :: Arr 'One a b) a
   |               ^
```

Presumably because the type family is expanded too late? This isn't very hard to work around but it took me a while to figure out why inference failed seemingly randomly from time to time.  
Thanks for reading!

By the way, is there a list of known issues anywhere so I don't report known ones?

**Comment by aspiwack** [comment]
I think this cannot be helped all that much. It is a conscious design choice of GHC that type families do not unfold easily (as unfolding a type family is translated to a coercion in core). The proper solution is to have an actual primitive multiplicity-parametric arrow type. Which is part of my second round of targets (but there is still quite a bit of work in the first round).

The current strategy to type an application `f u` (it predates linear types) is to see if `f` is inferred to be of type `A -> B`, in which case, `u` is type-checked at type `A`. If `f` is inferred to have another type `T`, then create new type variables `a` and `b`, infer the type of `u`, which is then unified with `a`, and `T` is unified with `a->b` (and as I understand it, this latter case is the one used when `f` is inferred at a type family`). In the latter case, I have to assume that the multiplicity is ω.

I agree that the error message is surprising though. Maybe I will be able to infer more precise multiplicities in the future.

There is a rough list of known issues in the README.

I'll close this. If you feel more discussion is useful, reopen.
