### ISSUE TITLE
Have a policy about linear kinds

### ISSUE THREAD

**Issue by mb64** [tweag/ghc#13]
At the moment, the compiler seems to accept but ignore linear kinds.
For example, this works:
```
{-# LANGUAGE KindSignatures #-}
data NormalType :: * -> *
data LinType :: * ⊸ *
class NormalClass (t :: * -> *)
class LinClass (t :: * ⊸ *)
instance NormalClass LinType
instance LinClass NormalType
```
Interactively, it only sometimes pretty-prints linear arrows in kinds:
```
λ> :k LinType
LinType :: * -> *
λ> :k LinClass
LinClass :: (* ⊸ *) -> Constraint
```
It would be better to explicitly error on a linear arrow trying to be used in a kind signature, as implementing linear kinds seems too much work for no benefit (as far as I can see -- maybe there's some use for it that I'm completely unaware of).

(I'm unfamiliar with codebase, but if pointed in the right direction, I'd be happy to give it a go at fixing myself.)

**Comment by aspiwack** [comment]
Thanks for pointing that out.

Well-kindedness is checked by a different procedure than well-typedness. I assumed I must have just ignored all multiplicity information in kind-checking, thinking it didn't matter. But you are right that it does. It is conceptually simpler, indeed, to complain about kinds with a linear arrow. Plus it is forward compatible if we decide to revert this decision. On the other hand, kinds and types are not differentiated in GHC, so it may be hard to actually implement. I'm guessing the most sensible choices are either to let `* ⊸ *` be an uninhabited kind, or to actually implement linearity in kind checking.

The main functions for kind checking are: [here](https://github.com/tweag/ghc/blob/linear-types/compiler/typecheck/TcHsType.hs#L454-L496) and [here](https://github.com/tweag/ghc/blob/linear-types/compiler/typecheck/TcHsType.hs#L519-L711). Not sure yet what would be the best approach to address this.

I don't know where the linearity information for `LinType` in your example is actually lost.

**Comment by mb64** [comment]
I made a pull request with a possible fix [here](https://github.com/tweag/ghc/pull/14).

**Comment by iamrecursion** [comment]
I was just thinking about how this restriction might interact with dependently typed haskell (`-XTypeInType`). Given that feature-flag has merged the language for types and kinds it might create some problematic interactions between this and dependent types (should both get accepted into GHC) if you disallow linear kinds.

**Comment by mb64** [comment]
@iamrecursion `-XTypeInType` allows datatype promotion to be kinds; however, you can only promote constructors, not variables (which you would need to do to somehow get something with a promoted linear arrow).  If you can find any weird type-hackery (no offense intended to any "weird type"-hackers out there) that somehow conflicts, or have any real-world possible use cases for linear kinds (most/all uses have to do with resource management, and there's not a lot of resources to manage in types), please comment.

With respect to
> (should both get accepted into GHC)
`-XTypeInType` is available in the linear branch, so feel free to try it out yourself!

**Comment by iamrecursion** [comment]
That's a very good point. Personally, I can't think of any real-world use cases for Linear Kinds (though that doesn't mean that none exist). 

I didn't think to try it out in the linear branch, so I may give that a go. I'll report back if I find any 'weird type hackery', as that's always good fun to mess around with.

**Comment by aspiwack** [comment]
Closing: if more discussion is needed, it should now move to ghc-proposals/ghc-proposals#91.
