### ISSUE TITLE
In Typeable, the multiplicity on arrows is ignored

### ISSUE THREAD

**Issue by aspiwack** [tweag/ghc#154]
When creating a dictionary for `Typeable (a ->_w b)`, the `w` is ignored. There should be an extra argument in the `EvTypeableTrFun` constructor, and it should be passed correctly by `TcInteract.doFunTy`.

**Comment by aspiwack** [comment]
I haven't come up with an example to demonstrate that this is broken. But it certainly is.

**Comment by monoidal** [comment]
Here's `unsafeCoerce`, based on https://ghc.haskell.org/trac/ghc/ticket/10000:

```
{-# LANGUAGE TypeFamilies, RankNTypes, LinearTypes #-}

module Unsafe where

import Data.Typeable

data T = T

data family F p

newtype instance F (Int -> Int) = ID (forall a. a -> a)
newtype instance F (Int ->. Int) = UC (forall a b. a -> b)

uc :: a -> b
uc = case cast (ID id) of Just (UC f) -> f
```

**Comment by aspiwack** [comment]
Great example :slightly_smiling_face:

**Comment by monoidal** [comment]
Done, #207 covers the followup fix for decomposition.
