### ISSUE TITLE
splitHsFun

### ISSUE THREAD

**Issue by aspiwack** [tweag/ghc#155]
The function `HsTypes.splitHsFunType` is missing cases for

- [ ] prefix linear arrow
- [x] prefix multiplicity-parametric arrow

**Comment by monoidal** [comment]
AFAICT, we don't have the prefix arrows yet.

**Comment by aspiwack** [comment]
Well, we have `(->.)` (that's the first bullet point), not the multiplicity parametric one. At least not in syntax, there is a type constructor for it.

**Comment by monoidal** [comment]
We consider supporting the prefix arrow in `splitHsFunTy` to be a mistake, and would like to remove it altogether: 
https://gitlab.haskell.org/ghc/ghc/issues/17211
I reverted support for `FUN` in #415.
