### ISSUE TITLE
Don't output any Unicode in error messages by default

### ISSUE THREAD

**Issue by mboes** [tweag/ghc#158]
Currently in the linear types branch error messages seem to report multiplicities using Unicode. The problem with this is that it creates operational difficulties in practice that are simply not worth the fight. Furthermore, Greek is arguably not user-friendly outside of PL wonks.

In particular, by default in a pure Nix shell the locale is not Unicode compliant. Because of this GHC is likely to panic if it *reads* or *writes* any file that contains Unicode. This often happens with e.g. unicode in .cabal files.

**Comment by aspiwack** [comment]
I think that this has been done. I'm not sure how to check. @monoidal I believe you fixed the latest of these occurrences, didn't you?

**Comment by monoidal** [comment]
There are a few left (easy to fix), can be found by grepping ω in the final diff.
