### ISSUE TITLE
Add a dedicated flag for printing multiplicities explicitly

### ISSUE THREAD

**Issue by aspiwack** [tweag/ghc#160]
Currently uses `-fprint-explicit-runtime-reps`. Needs a dedicated flag, as designed in the proposal.

The relevant function is: `IfaceType.eliminateMultiplicity`.

**Comment by aspiwack** [comment]
Or maybe we just want to gate this on `-XLinearTypes` instead. It sounds better than a mostly orthogonal flag.

**Comment by monoidal** [comment]
We now use `-XLinearTypes` since 82a40e09. Should this be closed?

**Comment by monoidal** [comment]
We've agreed with @goldfirere and Simon that we'll use `-XLinearTypes` for now.
