### ISSUE TITLE
Conversion to Unrestricted

### ISSUE THREAD

**Issue by jeltsch** [tweag/ghc#17]
The paper “Retrofitting Linear Types” mentions a function that converts values of types `a` into values of types `Unrestricted a`.

Is the intention that there is a function of type `a -> Unrestricted a` (or `a ->. Unrestricted a`)? I think this would be a bad idea, since it would make certain interesting uses of linear types impossible. For example, using linear types for capabilities relies on the guarantee that capabilities cannot be duplicated.

Or is the intention that there is some type class `C` and a function of type `C a => a -> Unrestricted a`? In this case, the capabilities issue, for example, could be solved by not making capability types instances of `C`.

**Comment by Tarmean** [comment]
If you define 

    data Undefined a where
        Undefined :: a -> Undefined a

Than we already have the constructor

    Undefined :: a -> Undefined a

Which can only be applied to values without linear context.

**Comment by jeltsch** [comment]
Right. I looked again into the “Retrofitting Linear Types” paper. Subsection 2.5 talks about a function that copies values from a “linear heap” to the ordinary, “dynamic” heap. For a particular type `T`, this function does not have type `T -> Unrestricted T`, but `T ->. Unrestricted T`. The question is whether the intention is to have a function of type `forall a . a ->. Unrestricted a` (which I think would be a bad idea) or to have a function of type `forall a . C a => a ->. Unrestricted a` for some type class `C`.

**Comment by Tarmean** [comment]
The [updated paper](https://github.com/tweag/linear-types/releases/download/v2.0/hlt.pdf) doesn't mention it - or  the two heaps - anymore. So I guess an api using linear types would look something like this now?

    withArray :: Int -> (MVec a -o Unrestricted r) -o Unrestricted r
    freezeArray :: MVec a -o Unrestricted (Vec r)

**Comment by aspiwack** [comment]
@Tarmean re: your PS. Indeed, it's a simplification that we did for the sake of the exposition in the paper. But it doesn't compose well if you don't return an `Unrestricted r` at the end.

@jeltsch there is no uniform function of type `a ->. Unrestricted a` in the system (having such a function amounts to saying that linear functions and unrestricted functions are isomorphic: declaring a function as linear would just adds syntactic clutter, not restrict the functions that you can write). But many types are equipped with such a function (for instance it is reasonably easy to write a function `[Bool] ->. Unrestricted [Bool]`. And it's probably worth it to have a type-class for such types.

**Comment by aspiwack** [comment]
Closing: the discussion should now move to ghc-proposals/ghc-proposals#91.
