### ISSUE TITLE
Use linear arrows in constructors with -XNoLinearTypes

### ISSUE THREAD

**Issue by monoidal** [tweag/ghc#173]
Currently, `data A a where MkA :: a -> A a` always creates the Unrestricted type.

Instead, it should do this only when `-XLinearTypes` is enabled, and create the multiplicity-polymorphic constructor otherwise.

Also reject `newtype B a where MkB :: a -> B a` when `-XLinearTypes` is on, we require `->.`.

**Comment by aspiwack** [comment]
For the MVP: we need to reject unrestricted newtypes.
