### ISSUE TITLE
Bad error message with multiplicity mismatch

### ISSUE THREAD

**Issue by monoidal** [tweag/ghc#199]
The following (wrong) code:

```
{-# LANGUAGE LinearTypes #-}
f :: a -->.(m) b
f = undefined :: a -> b
```

gives an error message:
```
    • Couldn't match type ‘'Omega’ with ‘'Omega’
      ‘m’ is a rigid type variable bound by
        the type signature for:
          f :: forall a b. a ->@[m] b
```

**Comment by monoidal** [comment]
`ghc -XLinearTypes X.hs` gives a good error message; `ghc X.hs` gives a bad error message, even though `X.hs` contains the LANGUAGE pragma.

**Comment by monoidal** [comment]
It looks like runtime reps have a similar problem, see https://ghc.haskell.org/trac/ghc/ticket/16050.

**Comment by aspiwack** [comment]
I assume a fix of one will fix the other.

It seems that somewhere there is a bit of code which is happy to default rigid variables. Which should never happen.

**Comment by aspiwack** [comment]
Though that seem different from the originally reported bug (which seems to be about instance-not-found error messages not mentioning kinds when it ought to)
