### ISSUE TITLE
Infer multiplicity of case and let

### ISSUE THREAD

**Issue by aspiwack** [tweag/ghc#20]
In the current implementation, `case` and `let` (and `where) are always non-linear when typed explicitely (they correspond to `case_ω` and `let_ω` in the paper formalisation.

_e.g._

```
λ> let f :: a ⊸ a; f x = case x of x -> x

<interactive>:27:19: error:
    • Couldn't match expected weight ‘1’ of variable ‘x’ with actual weight ‘ω’
    • In an equation for ‘f’: f x = case x of { x -> x }


λ> let f :: a ⊸ a; f x = let y = x in y

<interactive>:28:19: error:
    • Couldn't match expected weight ‘1’ of variable ‘x’ with actual weight ‘ω’
    • In an equation for ‘f’: f x = let y = x in y
```

The goal is to have linear versions of them. Experience shows that we expect the multiplicity index to be inferred, rather than being annotated. So that's how it is designed in the proposal.

There is no specification of how to infer these multiplicities yet.

**Comment by monoidal** [comment]
Closing - we now have upstream:#18738 and upstream:#18739.
