### ISSUE TITLE
Projections of newtypes

### ISSUE THREAD

**Issue by aspiwack** [tweag/ghc#21]
In the current implementation, projections of records always have a non-linear type:

```haskell
data P a b = P { p1 :: a, p2 :: b }
p1 :: P a b -> a
p2 :: P a b -> b
```

There are cases, however, where we could give projection a linear type: when all the other fields are unrestricted. A particularly common example is with `newtype` (where there is a single field):

```haskell
newtype N = N { unN :: A }
unN :: N -> A -- really expected to be N ->. A
```

We may want to handle at least the special-case of records with one field as its a common Haskell idiom.

**Comment by monoidal** [comment]
For backwards compatibility, we should have `unN :: N -->.(p) A`.

**Comment by monoidal** [comment]
I made some progress in the `record-projections`. This seems to work in ghci in simple cases but causes a lint failure during the build. It seems that when we build the selector we use `mkSimpleMatch` and in the end this ends up being a case-omega.

**Comment by aspiwack** [comment]
It's ok, it's not urgent: this is a backwards compatible change that we can add in later.

**Comment by monoidal** [comment]
Moved to https://gitlab.haskell.org/ghc/ghc/-/issues/18570.
