### ISSUE TITLE
Support for multiplicity-polymorphic datatypes

### ISSUE THREAD

**Issue by monoidal** [tweag/ghc#212]
```
data T a where MkT :: a -->.(p) T a
```
gives an ambiguity error. Currently we multiply all multiplicities in constructors, but we should really put a submultiplicity constraint. Also check `data T p a where MkT :: a -->. (p) T p a`.

**Comment by monoidal** [comment]
After #368, the following steps remain
- use `tcConArg` inside `kcConDecl`, currently there's code duplication (multiple calls to `tcMult`) -> done
- uncomment code in the test `MultConstructor` and add a few more examples (converting from `T Omega a` to `T One a`., creating and pattern matching on `T One a`, `T Omega a`, `T p a`) -> done, https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4193/diffs
- document that linear fields are generalized, multiplicity-polymorphic fields are not -> done, https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4271

**Comment by aspiwack** [comment]
Has this issue been closed because it's been solved a while ago? Or because of some upstream activity?

**Comment by monoidal** [comment]
The last point ("document that linear fields are generalized") on the todo list has just been merged.

**Comment by aspiwack** [comment]
May I ask for a link to the relevant MR?

**Comment by monoidal** [comment]
It's in the comment.

**Comment by aspiwack** [comment]
Right. I saw, as I clicked the button, that you had edited the comment above. I promptly deleted my comment hoping that it wouldn't generate a notification. But I was, evidently, too slow.
