### ISSUE TITLE
Allow prefix (->.)

### ISSUE THREAD

**Issue by monoidal** [tweag/ghc#215]
Allow prefix `(->.)`. The change can be based on #205.

**Comment by aspiwack** [comment]
In the current proposal (as of https://github.com/ghc-proposals/ghc-proposals/pull/356), there is no prefix notation to be had (safe for `FUN 'One`). So, let me close this.

**Comment by aspiwack** [comment]
Ah… unless we want `(⊸)` (Unicode only), as @monoidal pointed out to me elsewhere. Uh… probably?

**Comment by monoidal** [comment]
Moved to upstream:#19639.
