### ISSUE TITLE
Consider whether to limit use of FUN

### ISSUE THREAD

**Issue by monoidal** [tweag/ghc#216]
Currently, it's possible to import `FUN` and write a linear function without `-XLinearTypes`.

Should we allow this?

Yes: it's similar to allowing use of pattern synonyms without -XPatternSynonyms, it would require multiple limitations, for example given `Decompose (a b) = a` we can have `FUN = Decompose (->)`

No: linearity should not be allowed without `-XLinearTypes`.

Also check `data T m a where MkT :: FUN m a (T m a)`; this should probably raise an error message, currently it ignores `m`.

**Comment by monoidal** [comment]
Related to #379.

**Comment by goldfirere** [comment]
I think we should not allow prefix `FUN`. Similarly we should not allow prefix `(->)`.

**Comment by monoidal** [comment]
Closing: the part about GADT is done, the remaining check is covered by #379.
