### ISSUE TITLE
Handle pattern synonyms

### ISSUE THREAD

**Issue by aspiwack** [tweag/ghc#22]
Pattern-synonyms are not correctly implemented for linearly typed patterns.

That pattern-synonyms are bidirectional may cause additional type-checking challenges.

This has yet to be explored.

**Comment by aspiwack** [comment]
As discussed in the proposal, the current way pattern synonyms are desugared is not linear.

It means that having linear pattern synonym is beyond the scope of an MVP (but as far as I can tell, should be possible considering the specification of Core that we have).

First step: disallow.

**Comment by aspiwack** [comment]
In the current prototype, linear pattern synonyms can be defined, but they cannot be used in linear patterns, and used as term, they are, in fact, unrestricted.

```
Prelude> :set -XLinearTypes 
Prelude> :set -XPatternSynonyms 
Prelude> pattern Foo :: a ->. Maybe a ; pattern Foo x = Just x
Prelude> f :: a ->. Maybe a ; f x = Foo x

<interactive>:5:24: error:
    • Couldn't match type ‘'Omega’ with ‘'One’
        arising from an application
    • In an equation for ‘f’: f x = Foo x
Prelude> g :: Maybe a ->. (a, a) ; g (Foo x) = (x, x)

<interactive>:6:30: error:
    • Pattern synonyms are only allowed at multiplicity ω
    • In the pattern: Foo x
      In an equation for ‘g’: g (Foo x) = (x, x)
Prelude> 
```

**Comment by aspiwack** [comment]
It's a minor bug: I will not fix for MVP.

**Comment by monoidal** [comment]
Another minor bug: this shouldn't compile:

```{-# LANGUAGE LinearTypes, PatternSynonyms, GADTs #-}

data Unrestricted x where
  MkUnrestricted :: x -> Unrestricted x

pattern P :: a ->. Unrestricted a
pattern P x = MkUnrestricted x
```

Fortunately, the type of `P` is really unrestricted, so this cannot be used to violate linearity.

**Comment by monoidal** [comment]
One more observation: I think doing this will require syntax changes because of types.

```
id :: a ->. a
id x = x

nonlinear :: a -> a
nonlinear x = x

f1 (id -> x) = h x
f2 (nonlinear -> x) = h x
f3 (Unrestricted x) = h x
```

Note that `f1`, `f2`, `f3` use their argument in three different ways. `f1` is linear when `h` is, `f2` is never linear, `f3` is always linear. If those were patterns, I think one possibility would be:

```pattern P1 :: a # One -> a # One
pattern P2 :: a # Omega -> a # Omega
pattern P3 :: a # One -> a # Omega
```

**Comment by monoidal** [comment]
I moved the minor bug to upstream:#18806.

Not closing for now - after 18806 is fixed, I'd like to create a separate feature request for full pattern synonym support.

**Comment by monoidal** [comment]
Bug fixed, and full pattern synonym support is now tracked at upstream:#20184. Closing.
