### ISSUE TITLE
Optimisations change in T4945

### ISSUE THREAD

**Issue by aspiwack** [tweag/ghc#230]
The T4945 test is marked `expect_broken` in the linear type branch.

It doesn't actually retrigger T4945, SpecConstr occurs as it should. But further optimisation seem not to happen (it seems that master would specialise the join-point in which the SpecConstr'd function is defined to the one `STUArray` it's called with, which is a datacon application, making it possible to case-of-known-constructor away the remaining pattern-matching. This specialisation doesnt happen in the linear type branch). It's unclear really what changed, and why.

It's quite suspicious that it occurs precisely at the intersection of linear types and inline-datacon-wrapper-last (see #200): it fails in neither individually, but in the merge of both it fails. Maybe this reveals a subtle bug. Maybe it's actually nothing to worry about.

Though another difference that I noticed was that the SpecConstr'd `loop` function, in master, is turned into a join-point, but it isn't for no good reason in the linear type branch.

**Comment by monoidal** [comment]
Fixed by https://git.haskell.org/ghc.git/commitdiff/646b6dfbe125aa756a935e840979ba11b4a882c0
