### ISSUE TITLE
Newtype wrappers (probably) prevent a case-of-known-constructor in T5327

### ISSUE THREAD

**Issue by aspiwack** [tweag/ghc#235]
What's happening is not entirely clear to me. But it appears that the code is blocked on

```haskell
case val2 `cast` (T5327.N:Size[0] :: Size ~R# Int) of
{ GHC.Types.I# x_a2eO ->
```

Where `val2` is

```haskell
val1_r2fO `cast` (Sym (T5327.N:Size[0]) :: Int ~R# Size)
```

and `val2_r2fO` is

```haskell
val1_r2fO = GHC.Types.I# 17#
```

It seems to me that this should be a clear case of case-of-known-constructor. But it appear to fail. The only relevant difference which I can think of is that newtypes have wrappers in the linear-type branch. Though the wrapper does not show here, so maybe it's a red herring.

At any rate, if the case-of-known-constructor was effected, then we would have a `2# *# 17#` subexpression and it would, presumably, fold. And the test would pass again.

**Comment by monoidal** [comment]
Reported at Trac: https://ghc.haskell.org/trac/ghc/ticket/16254

**Comment by monoidal** [comment]
Fixed at https://gitlab.haskell.org/ghc/ghc/merge_requests/325/ and merged to linear-types branch.
