### ISSUE TITLE
Newtype wrappers (probably) prevent map/coerce reduction

### ISSUE THREAD

**Issue by aspiwack** [tweag/ghc#241]
And probably other coerce too.

The bottom-line is:

```haskell
newtype Age = Age Int

fooAge :: Array Int Int -> Array Int Age
fooAge = fmap Age
```

`fooAge` should be reduced to identity and isn't.

**Comment by monoidal** [comment]
Since this can occur in `master`, I created https://ghc.haskell.org/trac/ghc/ticket/16208.

**Comment by monoidal** [comment]
Fixed in https://git.haskell.org/ghc.git/commitdiff/646b6dfbe125aa756a935e840979ba11b4a882c0.
