### ISSUE TITLE
Template Haskell printing shows multiplicities in constructor

### ISSUE THREAD

**Issue by aspiwack** [tweag/ghc#242]
E.g.

```haskell
data Option a = Some a | None
$(reify 'Some >>= stringE . pprint)
```

Prints

```
"Constructor from Ghci1.Option: Ghci1.Some :: forall (n_0 :: GHC.Types.Multiplicity) (a_1 :: *) .\n                                             a_1 -> Ghci1.Option a_1"
```

I'm not sure whether it should be considered the right behaviour, or if we want to hide it as in #239 . But at any rate, if we want to print the multiplicity argument here, we at least need to respect its inferred status.

**Comment by monoidal** [comment]
> But at any rate, if we want to print the multiplicity argument here, we at least need to respect its inferred status.

I would argue that printing inferred variables without braces is not a linear types issue; this is present upstream. See also https://github.com/ghc-proposals/ghc-proposals/pull/179.

**Comment by aspiwack** [comment]
Fair enough. We will need guidance on this to decide whether it should be considered the right behaviour or not.

**Comment by monoidal** [comment]
It seems that this got worse:

```
λ> $(reify 'Some >>= stringE . pprint)

<interactive>:5:3: error:
    • Can't represent non-Omega multiplicity in Template Haskell: a
                                                                  -->.(n) Option a
    • In the untyped splice: $(reify 'Some >>= stringE . pprint)
```
