### ISSUE TITLE
hieFile support for multiplicity

### ISSUE THREAD

**Issue by monoidal** [tweag/ghc#269]
GHC got support for `hie` files, which can contain information about functions.

When merging this in #267, I didn't add support for non-Omega multiplicity. The situation is the same as for Typeable and TH. Unfortunately, this causes testsuite failures because of constructors.

**Comment by aspiwack** [comment]
What's an hie file?

**Comment by monoidal** [comment]
It's a new format that stores the results of typechecking and more. It's described at https://ghc.haskell.org/trac/ghc/wiki/HIEFiles and https://phabricator.haskell.org/D5239.

**Comment by monoidal** [comment]
Fixed by #309.
