### ISSUE TITLE
:info shows linear constructors

### ISSUE THREAD

**Issue by monoidal** [tweag/ghc#287]
Since #285, displaying a GADT using `:info` shows linear arrows even when `-XLinearTypes` is disabled. This can be fixed by adding another special case but I'm not sure if this is the best way to go.

**Comment by aspiwack** [comment]
What options are you seeing?

**Comment by monoidal** [comment]
If `-XLinearTypes` is disabled, we can just print the normal arrow. The problem is that it's one more place where we are specialcasing linear types. Ideally, this would reuse the logic of `defaultNonStandardVars` but I'm not seeing it.

**Comment by aspiwack** [comment]
It seems rather different algorithmically, indeed.

What does `-fprint-explicit-runtimes-rep` does when printing constructors?

**Comment by monoidal** [comment]
As far as I understand, printing of constructors is not affected by `-fprint-explicit-runtime-reps`. This is acceptable since levity polymorphism must be explicitly specified; with linearity, every constructor becomes implicitly linear. If we could print the wrapper (which has the multiplicity variable), we could then do defaulting.

**Comment by aspiwack** [comment]
I thought levity things were systematically hidden from users without `-fprint-explicit-runtime-reps`. In theory at least because:

```haskell
> :info ($)
($) ::
  forall (r :: GHC.Types.RuntimeRep) a (b :: TYPE r).
  (a -> b) -> a -> b
```

I suggest we don't care about this one too much.
