### ISSUE TITLE
Split CircleCI jobs in two 

### ISSUE THREAD

**Issue by facundominguez** [tweag/ghc#29]
According to https://circleci.com/gh/ghc/ghc/1558, it should be possible to create a workflow with two jobs:
 * One job for building GHC, taking near 2.5 hours, and
 * a follow up job for running tests which hopefully completes within the 5 hours timeout.

We could try uploading the whole directory tree to the workspace. If it takes too long, there must be a way to clean up the artifacts needed for building but not for testing.

**Comment by facundominguez** [comment]
meh, splitting might be unnecessary for circleci. It turns out the circleci configuration is not building with all the 8 available CPUs. Here is a (still ongoing) build which shows that ghc builds in almost half of the time when fixing that. https://circleci.com/gh/tweag/ghc/205

**Comment by mrkkrp** [comment]
This is great, I see it took 2:42 for the whole thing, we can probably close this issue then.

**Comment by mrkkrp** [comment]
We could actually follow the advice from GHC readme and use 9 threads:

> As a simple rule, you should have about N+1 jobs, where N is the amount of cores you have.

**Comment by facundominguez** [comment]
@mrkkrp, I followed your advice and the time was reduced some 10 minutes.  I have updated the PR.
