### ISSUE TITLE
'InvalidAbsDir "(unreachable)/"' while building using linear-GHC Stack Docker image

### ISSUE THREAD

**Issue by runeksvendsen** [tweag/ghc#30]
Hello there,

I'm trying to get linear GHC working with a project of mine, but after following [the instructions ](https://github.com/tweag/ghc/tree/linear-types#using-stack-with-the-docker-image) and running `stack build` I get the following error:

```bash
rune@macbook ufw (linear)*$ stack build
base-orphans-0.6: configure
base-orphans-0.6: build
mtl-2.2.1: configure
mtl-2.2.1: build
cabal-doctest-1.0.6: configure
call-stack-0.1.0: configure
base-orphans-0.6: copy/register
Progress: 4/31InvalidAbsDir "(unreachable)/"

InvalidAbsDir "(unreachable)/"

InvalidAbsDir "(unreachable)/"

InvalidAbsDir "(unreachable)/"
```

My `stack.yaml` looks like [this](https://github.com/runeksvendsen/ufw/blob/linear/stack.yaml).

And I'm trying to build [this](https://github.com/runeksvendsen/ufw/tree/linear) project (makes no use of linear arrows so far).

My Docker version is `18.03.0-ce-mac59 (23608)`

Do I need a special `base` to use linear GHC? I'm really only interested in having the type checker tell me if arguments annotated with `⊸` are indeed linear.

Thank you.

**Comment by aspiwack** [comment]
Hi @runeksvendsen ,

Thanks for your interest. I'm afraid that I can't reproduce. Could this be a Docker-for-mac issue? Could you maybe try in a virtual machine to see if the project builds there? I'm a bit at loss for the moment.

That being said, further down (when compiling `hashable`), I hit another issue, that I've encountered before: the version of `Typeable` in the prototype does not have the new typed typereps. Some dependencies fail. I should really update to a more recent `base`.

**Comment by runeksvendsen** [comment]
Hi @aspiwack,

Indeed it works fine (besides the `hashable` issue) on a Linux VM.

I'm thinking I will report this as a Stack bug as, judging by the output, this seems like an error that isn't handled properly by Stack.

Regardless, for playing around with linear arrows, it's sufficient for me to be able to build on a Linux VM, so I would really appreciate a fix of the `hashable`/`Typeable` issue, when/if you have the time.

**Comment by runeksvendsen** [comment]
I get the same error output when using the `fpco/stack-build` docker image for building, so this is definitely not an issue with the GHC in `tweag/linear-types`. Consequently, I'm closing this issue.

**Comment by aspiwack** [comment]
Thanks for investigating, I've opened #31 to address the `Typeable` issue. I don't have much time for the moment, but I'll try to do it soon.

**Comment by runeksvendsen** [comment]
@aspiwack Thank you! No rush.

For those interested, I've opened the following `stack` issue wrt. this issue: https://github.com/commercialhaskell/stack/issues/3948
