### ISSUE TITLE
Building using tweag/linear-types Docker image: "Unsupported extension: LinearTypes"

### ISSUE THREAD

**Issue by runeksvendsen** [tweag/ghc#301]
I'm using the `tweag/linear-types` Docker image to play around with linear types using Stack.

In my [source](https://github.com/runeksvendsen/ufw/blob/9d3d06a0eaab3fe92fc8910632703dd9973218f1/src/Data/UFW.hs#L12-L14) file I've added:

```haskell
frugal :: a ⊸ (a,a)
frugal a = (a,a)
```

If I *don't* add `{-# LANGUAGE LinearTypes #-}` to the top of the file, I get the error:

```
ufw-0.1.0.0: build (lib + exe)
Preprocessing library for ufw-0.1.0.0..
Building library for ufw-0.1.0.0..
[2 of 2] Compiling Data.UFW         ( src/Data/UFW.hs, .stack-work/dist/x86_64-linux-dkc68e43cf20ba48282b0ca96c3b2be50e/Cabal-2.0.1.0/build/Data/UFW.o )

/Users/runesvendsen/code/ufw/src/Data/UFW.hs:28:11: error:
    Not in scope: type constructor or class ‘⊸’
   |
28 | frugal :: a ⊸ (a,a)
   |           ^^^^^^^^^

/Users/runesvendsen/code/ufw/src/Data/UFW.hs:28:11: error:
    Illegal operator ‘⊸’ in type ‘a ⊸ (a, a)’
      Use TypeOperators to allow operators in types
   |
28 | frugal :: a ⊸ (a,a)
   |           ^^^^^^^^^


--  While building package ufw-0.1.0.0 using:
      /Users/runesvendsen/.stack/setup-exe-cache/x86_64-linux-dkc68e43cf20ba48282b0ca96c3b2be50e/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-linux-dkc68e43cf20ba48282b0ca96c3b2be50e/Cabal-2.0.1.0 build lib:ufw exe:ufw --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
Received ExitFailure 1 when running
Raw command: /usr/local/bin/docker start -a -i cbeec4e02f5b6820a7a0d0b144fa9891af20e5908ac3dc618d7ad67f27f96b97
```

and if I *do* try to enable `LinearTypes` I get the error:

```
ufw-0.1.0.0: build (lib + exe)
Preprocessing library for ufw-0.1.0.0..
Building library for ufw-0.1.0.0..

/Users/runesvendsen/code/ufw/src/Data/UFW.hs:4:14: error: Unsupported extension: LinearTypes
  |
4 | {-# LANGUAGE LinearTypes #-}
  |              ^^^^^^^^^^^


--  While building package ufw-0.1.0.0 using:
      /Users/runesvendsen/.stack/setup-exe-cache/x86_64-linux-dkc68e43cf20ba48282b0ca96c3b2be50e/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-linux-dkc68e43cf20ba48282b0ca96c3b2be50e/Cabal-2.0.1.0 build lib:ufw exe:ufw --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
Received ExitFailure 1 when running
Raw command: /usr/local/bin/docker start -a -i 83c99fe89174722d95c1386b024d5004bbc1fcccc9065b5932d2d348438dfaa9
```

This is the repo I'm working with: https://github.com/runeksvendsen/ufw/tree/linear

Here's the output of `docker images`:

```
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
tweag/linear-types   latest              56d06ef65768        3 weeks ago         1.97GB
```

**EDIT:** I should probably add that I'm on `OSX 10.13.6 (17G4015)` using `Docker Desktop (2.0.0.0-mac81 (29211)`  with `Docker 18.09.0`.

**Comment by runeksvendsen** [comment]
Activating `LinearTypes` seems to work fine. But trying to define `frugal` doesn't seem to work:

```
GHCi, version 8.7.20181203: http://www.haskell.org/ghc/  :? for help
Prelude> :set -XLinearTypes
Prelude> let { frugal :: a ⊸ (a,a); frugal a = (a,a) }

<interactive>:2:19: error:
    Not in scope: type constructor or class ‘⊸’

<interactive>:2:19: error:
    Illegal operator ‘⊸’ in type ‘a ⊸ (a, a)’
      Use TypeOperators to allow operators in types
```

**Comment by aspiwack** [comment]
I really need to fix this README, sorry. To use `⊸` you need `-XUnicodeSyntax`. Otherwise the syntax is `a ->. b` (notice the dot after the arrow).

Now that we've established that the docker image is indeed correct… maybe the original issue is in the `stack.yaml`? Could your share yours?

**Comment by runeksvendsen** [comment]
Thanks! No worries.

It works now. The issue was that the GHC version in the Docker image is 8.7, while my `stack.yaml` said `compiler: ghc-8.2`. After changing this to `compiler: ghc-8.7` it works like a charm.

So, in other words, entering the wrong GHC version for the `compiler` option in `stack.yaml` seems to make Stack use a plain GHC version (which doesn't support `LinearTypes`), hence the error.

**Comment by runeksvendsen** [comment]
Here's a BASH one-liner for getting the `stack.yaml` `compiler:` version from the `linear-types` Docker image (may be useful for the README):

    docker run tweag/linear-types | egrep -o "version \d.\d" | sed 's/version /compiler: ghc-/'

**Comment by monoidal** [comment]
`README` is now updated, I believe this finishes the ticket.
