### ISSUE TITLE
Type signature omits linearity check

### ISSUE THREAD

**Issue by monoidal** [tweag/ghc#329]
This shouldn't work:

```
{-# LANGUAGE ExplicitForAll, ScopedTypeVariables, LinearTypes #-}
f :: forall a. a ->. (a,a)
f x = let y :: a; y = x in (y,y)
```

Similar to #142; the type signature is important.

**Comment by aspiwack** [comment]
Smaller example:

```haskell
{-# LANGUAGE LinearTypes #-}
f x = let y :: Bool -> Bool; y = x in (y,y)
```

**Comment by aspiwack** [comment]
Sorry, this omits specifying linearity, so of course it passes.

The following passes though, so we don't :

```haskell
{-# LANGUAGE LinearTypes #-}
f :: (Bool->Bool) ->. (Bool->Bool , Bool->Bool)
f x = let y :: Bool->Bool; y = x in (y, y)
```

Scoped type variables are not necessary for this example.

**Comment by aspiwack** [comment]
And it passes core lint.

**Comment by aspiwack** [comment]
The generated core is:

Before desugar optimisation

```haskell
f['Omega] :: (Bool -> Bool) ->. (Bool -> Bool, Bool -> Bool)
[LclIdX]
f['Omega]
  = \ (x_aXc['One] :: Bool -> Bool) ->
      letrec {
        y_aXd['Omega] :: Bool -> Bool
        [LclId]
        y_aXd['Omega] = x_aXc['One]; } in
      (y_aXd['Omega], y_aXd['Omega])
```

after optimisation

```haskell
f['Omega] :: (Bool -> Bool) ->. (Bool -> Bool, Bool -> Bool)
[LclIdX]
f['Omega]
  = \ (x_aXc['One] :: Bool -> Bool) -> (x_aXc['One], x_aXc['One])
```

**Comment by aspiwack** [comment]
I can confirm that a binding with a type signature passes through a quite different code-path than one without a type signature.

Without a type signature we end up in `tcMonoBinds`, which handles the scaling appropriately. I'm currently investigating `tcPolyCheck` which is used to check bindings with type signatures. I should soon find what should be scaled.

**Comment by aspiwack** [comment]
Ok so, here's a thing: in `tcMonoBind` we scale the usage environment after exiting `tcMatchesFun`. We don't in `tcPolyCheck`.

But as these two functions call `tcMatchesFun`, I'm wondering it it'd be possible to push the scaling down to `tcMatchesFun`.

**Comment by aspiwack** [comment]
There is a third call to `tcMatchesFun`: in `tcRhs`. I don't know (or don't remember) what this function does. It doesn't have any scaling in it, though. But it does look potentially feasible to factor in the scaling.

**Comment by aspiwack** [comment]
Mmm… curious. `tcRhs` is also used in `tcMonoBinds`. And also followed by a scaling.

All these scaling are by `Omega`. Suggesting that these functions are only used for the checking of let-bindings and, probably, case scrutinees. I'm not sure whether I can justify pushing the scaling to `tcMatchesFun` yet. But it does look quite reasonable. Also simplifies the code a little.
