### ISSUE TITLE
Followup work to Core Lint issue

### ISSUE THREAD

**Issue by monoidal** [tweag/ghc#335]
- [x] The following code fails Lint with -O
```
{-# LANGUAGE  NoImplicitPrelude, BangPatterns #-}

module Real2 where

import GHC.Base
import GHC.Num

data  Ratio a = R !a

properFraction      :: (Num a, Num b) => (a -> (a, Integer)) -> Ratio a -> (b, Ratio a)
properFraction quotRem (R x) = let (q, t) = quotRem x in (fromInteger t, R (q+q))

ceiling :: (Num b, Num a) => (a -> (a, Integer)) -> (Ratio a -> a -> Bool) -> Ratio a -> (b, Bool)
ceiling quotRem e x = let !z = 0 in case properFraction quotRem x of (n, r) -> (n,  r `e` z)
```
- [x] The following code fails Lint with -O:
```
module F where

formatRealFloatAlt :: Int -> Int ->  Int
formatRealFloatAlt dec e = case roundTo dec (replicate e 0) of (_,is) -> is
 
roundTo :: Int -> [Int] -> (Int,Int)
roundTo d [] = case replicate d 0 of [x] -> (x, x)
```
- [x] The following code fails Lint with -O
```
module Distribution.Types.BuildInfo  where

data BuildInfo = BuildInfo {
       cppOptions        :: [String],  -- ^ options for pre-processing Haskell code
       asmOptions        :: [String],  -- ^ options for assmebler
       cmmOptions        :: [String],  -- ^ options for C-- compiler
       ccOptions         :: [String],  -- ^ options for C compiler
       cxxOptions        :: [String],  -- ^ options for C++ compiler
       frameworks        :: [String], -- ^support frameworks for Mac OS X
       cxxSources        :: [String],
       jsSources         :: [String]
   }


data Executable = Executable {
       buildInfo  :: BuildInfo
   }


data Component = CLib   Executable
              | CFLib  Executable
              | CExe   Executable
              | CTest  Executable
              | CBench

foldComponent (CLib   lib) = buildInfo lib
foldComponent (CFLib  flib)= buildInfo flib
foldComponent (CExe   exe) = buildInfo exe
foldComponent (CTest  tst) = buildInfo tst
```
- [x] Currently the test OldList is failing Lint. This is because it relies on the tcSubMult rule `p*q <= r <=> p <= r, q <= r`, which is present in typechecker but not in Lint. Solutions: (a) add the tcSubMult rule to Lint (b) remove the tcSubMult rule. If we do (b) then valid H98 programs (no linear types) fail to compile, such as:
```
module OldN where

sequences = ascending (True:)

ascending f = asTypeOf (ascending (\ys -> f (True:ys))) sequences
```
(taken from Data.OldList)
- [x] Fix the hack for aliases. In 3e6225dadc9e1411, we should give an error in the "bad alias" case. (Test cases to check: T14304 ado001)
- [x] Fix wrappers: remove the p*p = p rule.
- [x] Fix linearity checks: base/GHC/Event/PSQ.hs
- [x] Fix linearity checks: case-of-case (exposed by worker-wrapper)
- [x] Fix linearity checks: SetLevels
- [x] Fix linearity checks: CSE
- [x] Fix linearity checks: LinearPolyType (moved to #354)
- [x] Fix linearity checks: linear if (Linear3)
- [x] Fix linearity checks: make aliases count as unrestricted
- [x] Fix linearity checks: remove normalisation from Core Lint
- [x] Fix remaining occurrences of `varWeight` (best done after fixing aliases. Idea: try removing `varWeight` from Core Lint first)
- [x] Fix assertion failure for T2334A (newtype with two fields)
- [x] Fix assertion failures with unboxed sums and tuples (dataConInstOrigArgTys; there's a working hack in `assertions` branch)
- [x] Think what can be done with Core Lint. Can we give an error when the output is Nothing but there are no errors? Unit tests?

**Comment by aspiwack** [comment]
Great! This is much better!
