### ISSUE TITLE
Type inference fails before a cast can be inserted

### ISSUE THREAD

**Issue by mpickering** [tweag/ghc#34]
We consider this silly widget `or`. The key feature is that we are abstracting of types of kind `* -> * -> *`. 

```
{-# LANGUAGE NoImplicitPrelude #-}
module Dollar where
{-
inplace/bin/ghc-stage1 -O2 -dcore-lint
See in Control.Arrow and Data.Functor.Contravariant
-}

import GHC.Base

class Or p where
	or :: p a b -> p a b -> p a b

instance Or (->) where
	or x _ = x
foo = or Just (\x -> Just x)
```

Then consider what happens if we use `or` with a linear type as its first argument and an unrestricted arrow on the second argument. The way the type checker works, `p` will be instantiated to `-o` by the first argument which will then not match the type of the second argument and type checking fails. 
This is the error message (which mentions `-o` when the user program does not). 

````
{-
[1 of 1] Compiling Dollar           ( linear-tests/Op.hs, linear-tests/Op.o )
linear-tests/Op.hs:18:16: error:
    • Couldn't match expected type ‘a ⊸ Maybe a’
                  with actual type ‘a0 -> Maybe a0’
    • The lambda expression ‘\ x -> Just x’ has one argument,
      its type is ‘p0 a b0’,
      it is specialized to ‘a ⊸ Maybe a’
      In the second argument of ‘or’, namely ‘(\ x -> Just x)’
      In the expression: or Just (\ x -> Just x)
    • Relevant bindings include
        foo :: a ⊸ Maybe a (bound at linear-tests/Op.hs:18:1)
   |
18 | foo = or Just (\x -> Just x)
   |                ^^^^^^^^^^^^
-}
```

We might hope that the typechecker inserts a cast to eta expand `Just` so that it has an non-linear type but this is not currently how it operates and is probably difficult in general.

**Comment by runeksvendsen** [comment]
Perhaps I misunderstand the relationship between `->` and `⊸`, but if we imagine there were an `Or` instance looking like this

```haskell
instance Or (⊸) where
	or _ y = y
```

how would GHC know which `Or` instance to pick for the expression `foo = or Just (\x -> Just x)`?

Seems to me like this is indeed not supposed to type check, according to the definition of the `Or` class.

**Comment by mpickering** [comment]
Of course you're right. The instance for `(->)` is a red herring. It is phrased in this way because the promise of linear haskell is to not interfere unless asked to.

**Comment by aspiwack** [comment]
Yep. It was. Or at least: it is
