### ISSUE TITLE
Core Lint issue in integer-gmp

### ISSUE THREAD

**Issue by monoidal** [tweag/ghc#356]
The following file, taken from GHC.Float and multiple files in integer-gmp, causes a Core Lint error:

```
{-# LANGUAGE MagicHash, UnboxedTuples #-}

module Prob where

import GHC.Prim

fromRat'' :: (Int# -> Int#) -> Int# -> Int#
fromRat'' d i =
    case integerLog2IsPowerOf2# d i of
      (# _, _ #) -> 0#

integerLog2IsPowerOf2# :: (Int# -> Int#) -> Int# -> (# Int#, Int# #)
integerLog2IsPowerOf2# f k = (# f k, test k #) 
  where
    test :: Int# -> Int#
    test i = case f i of
                 0# -> test (i -# 1#)
                 _   -> 1#
```

**Comment by monoidal** [comment]
This is caused by:

```
-- Simplify a join point, adding the context.
-- Context goes *inside* the lambdas. IOW, if the join point has arity n, we do:
--   \x1 .. xn -> e => \x1 .. xn -> E[e]
-- Note that we need the arity of the join point, since e may be a lambda
-- (though this is unlikely). See Note [Case-of-case and join points].
simplJoinRhs :: SimplEnv -> InId -> InExpr -> SimplCont
             -> SimplM OutExpr
simplJoinRhs env bndr expr cont
  | Just arity <- isJoinId_maybe bndr
  =  do { let (join_bndrs, join_body) = collectNBinders arity expr
        ; (env', join_bndrs') <- simplLamBndrs env join_bndrs
        ; join_body' <- simplExprC env' join_body cont
        ; return $ mkLams join_bndrs' join_body' }
```

We have a join point `\(x # One) -> x`, boring context E[e] = const and transform to `\(x # One) -> const` which is no longer linear. We need to scale `join_binds` by `contHoleScaling cont`.

**Comment by aspiwack** [comment]
Mmm… yeah… join point inlining can be curious. We need to think about this carefully though. I'm keeping this as a high priority task on Thursday (holiday tomorrow).

**Comment by aspiwack** [comment]
Ok, I've reviewed the corresponding code. And you are entirely right. The commutation of a join point with a continuation is parallel, and must be consistent with, the commutation of a case with the same continuation.

Since we are scaling the binders of the case, we also need to scale the (corresponding) binders of the join point.

A line about this should be dropped in `Note [Case-of-case and join points]`.
