### ISSUE TITLE
-XNoLinearTypes should mean no linear types

### ISSUE THREAD

**Issue by goldfirere** [tweag/ghc#379]
As discussed with Arnaud and @monoidal, `-XNoLinearTypes` really should mean that there are no linear types in the module. This means:

- No local identifiers are bound linearly.
- No functions are inferred to have linear types.

This probably means that the `tcCollectingUsage` stuff can be skipped in modules with `-XNoLinearTypes`, improving performance.

**Comment by aspiwack** [comment]
We don't know that performance is an issue at all, yet. So we can't know whether such an optimisation would affect performance in a visible way.

However, this is proposed to be consistent with other similar extensions, like GADTs: one can't pattern match on a GADT constructor without `-XGADTs` enabled.

I'm not sure yet how this is best implemented.

**Comment by monoidal** [comment]
> No functions are inferred to have linear types.
We agreed to drop this. Instead, the restrictions on inferred multiplicity variables will follow the levity polymorphism or monomorphism restriction route.

**Comment by monoidal** [comment]
After further discussion, we'd like to change this ticket. Just like now, allow linear binders even if `-XLinearTypes` is not enabled. However, we disallow type signatures (using a type synonym), or inferred types (for `let` and top-level values) that mention linear types with `-XNoLinearTypes`. See also https://gitlab.haskell.org/ghc/ghc/issues/17213

**Comment by aspiwack** [comment]
@monoidal do we still have (known) infelicities with respect to this ticket? Otherwise let's close.

**Comment by monoidal** [comment]
I added this as a bullet point to upstream:#18469 which covers this issue and more.
