### ISSUE TITLE
Undiagnosed error with levity polymorphism checking - 

### ISSUE THREAD

**Issue by mpickering** [tweag/ghc#39]
- T13233 - A very mysterious isUnliftedType panic. This function is used all over the compiler, I couldn't get a foothold to start debugging this yet.
- T13244 - Looks like the same as T13233 but less mysterious

```
=====> T13244(normal) 1 of 1 [0, 0, 0]
cd "./indexed-types/should_compile/T13244.run" &&  "/root/ghc-linear/inplace/test   spaces/ghc-stage2" -c T13244.hs -dcore-lint -dcmm-lint -no-user-package-db -rtsopts -fno-warn-missed-specialisations -fshow-warning-groups -fdiagnostics-color=never -fno-diagnostics-show-caret -dno-debug-output  
Compile failed (exit code 1) errors were:

T13244.hs:34:9: error:
    A levity-polymorphic type is not allowed here:
      Type: Unboxed Int
      Kind: TYPE (Rep Int)
    When trying to create a variable of type: Unboxed Int

*** unexpected failure for T13244(normal)

Unexpected results from:
TEST="T13244"
```

Could be to do with the eta-expansion shenanigans?

**Comment by mpickering** [comment]
Yes - this is to do with the eta expansion.

Looking at `T13244` makes this clear where we have 

```
box :: Int# -> Int
box = I#
```

It is not ok to eta-expand `I#` to make it an unrestricted type because then we get.

```
box = \y -> I# y
```

But the type of the binder `y` is then `Unboxed Int` which is apparently not allowed. I shan't worry about this too much now as we are going to get rid of this eta-expansion.

**Comment by aspiwack** [comment]
Probably already fixed.

**Comment by aspiwack** [comment]
This is actually not fixed yet. It may be because of the wrappers around additional constructors. I don't know yet.

**Comment by aspiwack** [comment]
I believe that solving this will also solve the panic in #162 (the reasoning is that the difference, in the PR, is that there are more unboxed types exposed (in that case `(~#)`).

**Comment by aspiwack** [comment]
T13244 has been independently resolved though. But T13233 still has failures.

**Comment by aspiwack** [comment]
Still. The error has changed. It now panics in `setNeverLevPoly`, and fails with a type errors in a handful of other places. Not sure why that is. I'm still working under the assumption that the problem is wrappers around unboxed constructors. But I'm not entirely sure anymore.

**Comment by aspiwack** [comment]
I'm starting to think that I'm mistaken: constructors with unboxed arguments always had wrappers, _e.g._ when they are GADTs.

Also, I notice that the issue in T13233 also happens around a use of `mkWeak#` which is not a constructor anyway.

**Comment by aspiwack** [comment]
The error message on T13233 is, by the way,

```
ghc: panic! (the 'impossible' happened)
  (GHC version 8.7.20181026 for x86_64-unknown-linux):
       ASSERT failed!
  forall a b. a -> b -> (# a, b #)
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/utils/Outputable.hs:<line>:<column> in <package-id>:Outputable
        pprPanic, called at compiler/utils/Outputable.hs:<line>:<column> in <package-id>:Outputable
        assertPprPanic, called at compiler/basicTypes/IdInfo.hs:<line>:<column> in <package-id>:IdInfo
        setNeverLevPoly, called at compiler/basicTypes/MkId.hs:<line>:<column> in <package-id>:MkId
```

(I just realised that the type errors I was seeing were the error message that _should_ have been observed not unexpected errors. Today will not be remembered as the day where I had the clearest of minds)

**Comment by aspiwack** [comment]
This note in `MkId` seems relevant: 

> NB: unboxed tuples have workers, so we can't use
> setNeverLevPoly

`setNeverLevPoly` is the function that panics. It records the fact that an identifier doesn't have any levity polymorphism. It panics when the "return type" of the identifier may be levity polymorphic. In our case: `(#,#)` is levity polymorphic because it can take fields of any multiplicities.

We should never be calling `setNeverLevPoly` on unboxed tuples. But we are. Probably because we have introduced wrapper around them. Maybe my first intuition was right after all.

**Comment by aspiwack** [comment]
For the records, I should say that unboxed tuples (or sums) shouldn't have workers, because a worker would have type `forall rep1 rep2 (a :: TYPE rep1) (b :: TYPE rep2). a -> b -> (# a, b #)`. However, this is _not_ a legal function type in Haskell! The levity polymorphic restriction imposes that no variable have levity polymorphic kinds.
