### ISSUE TITLE
Add a pass converting case[1] to case[Omega]

### ISSUE THREAD

**Issue by monoidal** [tweag/ghc#407]
The branch that changes wrappers causes `case[1]` to appear in Core much more often.
Not all optimizations are valid with `case[1]`.
@aspiwack suggested that we can have an extra step (perhaps during rebuilding of case), which converts `case[1] x[Omega] of` to `case[Omega] x[Omega] of`.

**Comment by aspiwack** [comment]
Moved to upstream:#18471.
