### ISSUE TITLE
Make varMult and varUsages into one

### ISSUE THREAD

**Issue by aspiwack** [tweag/ghc#435]
I currently have two fields in `Var`, one for multiplicity annotation (for lambdas, and case-expressions) and one for usage annotation (for let binders).

Exactly one of them is useful at a given time. So instead, it would be preferable to have a single field with is either a multiplicity or a usage annotation.

I've done the ground work here: https://github.com/tweag/ghc/tree/lt/mult-or-usages . But it turns out that tracking all the places where new identifiers are lambdas or lets (or one becomes the other!) is long and tedious.

So in the interest of time, I've preferred keeping the two fields, at the price of imprecisions, but hopefully only in linear code.

**Comment by aspiwack** [comment]
Note: the `fix_float` business in `SimplEnv` will need to be reverted. It'll be hard to forget though, as it will probably blow up in our faces.

**Comment by monoidal** [comment]
Closing as subsumed by upstream:#18694. I mentioned this issue in the comment so that it won't get lost.
