### ISSUE TITLE
Instantiate inferred arguments only

### ISSUE THREAD

**Issue by monoidal** [tweag/ghc#438]
The current branch instantiates all type arguments when VTA is not possible. 

As discussed, change it to instantiate just inferred arguments.

**Comment by aspiwack** [comment]
Should this have the blocker tag?

**Comment by monoidal** [comment]
Yes.

**Comment by aspiwack** [comment]
What is the status of this? I don't really understand what the issue is about.

**Comment by monoidal** [comment]
Not done. The issue is about typechecking of datacons in `return_data_con`. Currently we instantiate if a datacon has stupid theta or it's levity-polymorphic (unboxed tuples, sums, newtypes). In a past discussion we had, the idea was to instantiate arguments which are inferred, this would remove the exception for levity polymorphism.

**Comment by aspiwack** [comment]
Can you write the gitlab issue for this? It's not clear enough in my head for me to write it. And this looks like an issue which should be up there sooner rather than later.

**Comment by monoidal** [comment]
Moved to upstream:#18481.
