### ISSUE TITLE
Haddock does not print a linear arrow #->

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/ghc#463]
In [this branch of linear base](https://github.com/tweag/linear-base/tree/module-docs) running `stack --nix haddock` yields documentation that doesn't use the linear arrow when it should. This would be awesome to have working :smile: 

Note: I believe this issue isn't specific to the version in the nix package archive used in linear-base.

**Comment by monoidal** [comment]
Haddock PR: https://github.com/haskell/haddock/pull/1238

**Comment by monoidal** [comment]
The haddock MR has been merged a long time ago. I see linear arrows with `stack --nix haddock` and on https://hackage.haskell.org/package/linear-base.
