### ISSUE TITLE
Investigate hs-boot imports

### ISSUE THREAD

**Issue by goldfirere** [tweag/ghc#482]
GHC cannot inline through hs-boot imports. If a hot code path uses an hs-boot import, this fact may drastically impact performance.

In particular, the pattern synonyms `One` and `Many` use `eqType` via an hs-boot import. This just might be a problem that would manifest as an increase in time spent but not an increase in allocations, which is a problem we're seeing. In all truth, I don't think this `eqType` is the culprit, but we should investigate. In this particular case, we're probably better off using something more specialized (and efficient) instead of `eqType`, which does a fair amount of work unnecessary in this use case.

**Comment by aspiwack** [comment]
I think we've done this. @goldfirere do you still have plans for this issue, or should we close?

**Comment by goldfirere** [comment]
Keep open: now that linear types has merged(!), we should transfer this and other tickets about performance improvements to GHC. So I would wait to close this until after we've opened those GHC tickets.

**Comment by goldfirere** [comment]
@goldfirere ping.

**Comment by goldfirere** [comment]
Moved upstream: https://gitlab.haskell.org/ghc/ghc/-/issues/19108
