### ISSUE TITLE
Pattern guards can break linearity.

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/ghc#491]
**Describe the bug**
Linearity doesn't work with pattern guards.

**To Reproduce**

This typechecks but should not:

```
{-# LANGUAGE LinearTypes #-}

unsafeConsume :: a #-> ()
unsafeConsume x | _ <- x = ()
```

Tested on the GHC from this commit of linear base:
79b7aa1f4eebc5c66730f35789f29747659afc58

This was the GHC from the linear branch on December 20th, 2019.

**Comment by aspiwack** [comment]
A reminder to self: one thing which can be done is to look for occurrences of `tcSyntaxOp` where the multiplicity may be mishandled. I've fixed a few bugs around that today.

(pattern guards, if I remember correctly, use the same syntax as the do notation, it's not the same typechecking path though, so it may not use `tcSyntaxOp`, to be investigated later).

**Comment by aspiwack** [comment]
Now tracked as upstream:#18439.
