### ISSUE TITLE
Template Haskell does not detect linearity

### ISSUE THREAD

**Issue by monoidal** [tweag/ghc#504]
```
import Language.Haskell.TH

idenq :: TExpQ (() #-> ())
idenq = [|| \x -> x ||]
```

fails to compile

```
    • Couldn't match type ‘'Many’ with ‘'One’
      Expected: TExpQ (() #-> ())
        Actual: Q (TExp (() -> ()))
    • In the Template Haskell quotation [|| \ x -> x ||]
      In the expression: [|| \ x -> x ||]
      In an equation for ‘idenq’: idenq = [|| \ x -> x ||]
  |
8 | idenq = [|| \x -> x ||]
  |         ^^^^^^^^^^^^^^^
```
Reported at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/852#note_280765

Ticket https://gitlab.haskell.org/ghc/ghc/-/issues/18211 might be related.

**Comment by aspiwack** [comment]
It does look like the opposite of upstream:#18211: in our case, it appears that the type of the quasi-quotation is inferred not checked. But then again, upstream:#18211 is about splices, this is about quasiquotations to the mix. May still be related, though.

**Comment by monoidal** [comment]
Moved to upstream:#18736.
