### ISSUE TITLE
Let ordering renders linearity very fragile

### ISSUE THREAD

**Issue by mpickering** [tweag/ghc#51]
The optimiser introduces lets for many things. However, in the presence of linearity this is extremely fragile. 

```
let x[w] = .. in let y[1] = ... in y
```
Is accepted but reordering the variables (which is safe if `x` is not used in `y`) causes a linearity failure as the single usage of `y` is scaled by `w`.

```
let y[1] = ... in let x[w] = ... in y
```
Perhaps we want to try to float linear lets in as far as possible or only scale variables which are actually used by `x`.

**Comment by mpickering** [comment]
Yes that's right. I realised that I was scaling the wrong environment.. the rule is now.

```
body_ue `addUE` (l_weight `scaleUE` let_ue)
```

**Comment by aspiwack** [comment]
You also need to remove the variable from the usage environment (and check its linearity).

(I was just catching up with my emails, I didn't realise that this was the issue you already said had been fixed)

**Comment by mpickering** [comment]
Is removing it to account for shadowing?

**Comment by aspiwack** [comment]
Well, indeed, I suppose that if there is no shadowing, you can get away with not removing the binder from the usage environment at all.

I didn't think of this. It just makes more sense semantically, in my head: the usage env is the usage of the free variables of some expression.
