### ISSUE TITLE
Address all the « arnaud » and « MattP » notes

### ISSUE THREAD

**Issue by aspiwack** [tweag/ghc#57]
Throughout the code, we've left notes with the word « arnaud » or « MattP » (most often of the form `-- TODO: arnaud:`).

Before we propose the patch for review, we need to make sure that they have all been cleaned up.

**Comment by aspiwack** [comment]
I'm resolving these, but I'm still leaving a few:

- Template Haskell (see also #66 )
- Vectorise (they will auto disappear when faee23bb69ca813296da484bc177f4480bcaee9f is merged)
- Haddock (in large part because it's a submodule)

**Comment by aspiwack** [comment]
In [build #1698](https://circleci.com/gh/tweag/ghc/1698), I seem to have messed up some out of bound things. (It's not too surprising this one has actual logic in it, which I implemented a tad blindly).

I'll analyse soon. But the errors are not spurious.

Reproduce locally with:

```
make TEST="T7857 rebindable6 tcfail040" test
```

**Comment by aspiwack** [comment]
That failure comes from the fact that `GHC.Types.Omega` is considered out of scope, despite it being declared as wired-in.

Being in scope is defined as:

```haskell
    name_in_scope name
      | isBuiltInSyntax name
      = True -- E.g. (->)
      | Just mod <- nameModule_maybe name
      = qual_in_scope (qualName sty mod (nameOccName name))
      | otherwise
      = True
```

And being built-in syntax is defined as:

```haskell
isBuiltInSyntax :: Name -> Bool
isBuiltInSyntax (Name {n_sort = WiredIn _ _ BuiltInSyntax}) = True
isBuiltInSyntax _                                           = False
```

I'm not sure yet how this is possible.

**Comment by aspiwack** [comment]
Oooh! Built-in is stronger than `WiredIn` I didn't realise it. `WiredIn` can be either `BuiltInSyntax` or `UserSyntax`. And `Omega` is declared as `UserSyntax`. Next step: see if it is reasonable to declare it `BuiltIn`, or if we must use another trick.

This seems to be different than `RuntimeRep`-s in that the `RuntTimeRep`-s argument of an arrow are not traversed for free variables (because they are inferred, I suppose, hence actually come from somewhere else where they would be traversed). Also maybe `*` is actually `BuiltInSyntax`. Otherwise, I'm not sure how it would work when we use `*` in a signature.

But since we need to traverse multiplicities, and we _can't_ require that an extra file be imported for multiplicities (we at the very least need to be Haskell98 compliant (even with `-XNoImplicitPrelude`, too). We need to resort to some other trick.

**Comment by aspiwack** [comment]
`*` is actually `UserSyntax`. `BuiltInSyntax` has few representatives, and includes `[]`, `(:)`, tuples, as well as unboxed tuples and sums. So going built-in for `Omega` doesn't seem like it's the right solution.

I'll think it over.

**Comment by aspiwack** [comment]
Mmm… this is subtle… `*` and `Type` actually require importing a file if you are using `TypeInType` (namely `Data.Kind`). But `*` is syntax otherwise.

I'll try with making `Omega` built-in. And hope that there is no undesirable consequences.

**Comment by aspiwack** [comment]
Ah, and all the primitive type (the `foo#`) built-in too (as, evidently, they are not defined anywhere).

**Comment by aspiwack** [comment]
To reproduce the failures in [build #1699](https://circleci.com/gh/tweag/ghc/1699):

 ```
make TEST="T11334b T13398a T14055 T7805 T7857 T9359 rebindable6 tcfail040" test
```

(it actually includes the tests from the previous build, but it's still fast enough)

**Comment by aspiwack** [comment]
Ok. So. This one seems to be about the fact that using `Omega` in a type requires `TypeInType`. And, as above, it is used implicitly by the arrow. And, in some case, this is detected and raises an error.

**Comment by aspiwack** [comment]
Turns out this was easy: there is already a mechanism for automatically promoted types. Namely the `kindTyConKeys` set.

**Comment by monoidal** [comment]
I left a few `TODO Krzysztof` notes (they should be just checking if multiplicity is correct).
