### ISSUE TITLE
Add linearity tests to the test suite

### ISSUE THREAD

**Issue by aspiwack** [tweag/ghc#58]
We've come up with a number of tests for linearity features.

They are in the `linear-tests/` directory of the Linear GHC sources. As well as in [this file](https://github.com/tweag/linear-types/blob/195388869a97d2904c11891e319c04403ee2e1d9/Tests/test.hs).

We must

- [ ] Make all these tests into proper test suite tests
- [ ] Remove the `linear-tests/` directory

**Comment by mpickering** [comment]
In some ways this is unnecessary as all the tests in there have come from the testsuite. That is why I have been a bit lax about minimising examples.

**Comment by aspiwack** [comment]
Well, there may be some variants, or personal addition, plus there is the other test file. At any rate, we should have some tests, and the `linear-tests/` directory must be cleaned. Eventually.
