### ISSUE TITLE
Make Template Haskell compatible with linear types

### ISSUE THREAD

**Issue by aspiwack** [tweag/ghc#66]
We've been mostly ignoring Template Haskell for the moment.

We will have to make sure that Template Haskell understands the new syntax for linear types.

- [ ] Linear arrow constructor
- [ ] Multiplicity-polymorphic arrow constructor
- [ ] Linear arrow in GADT constructions
- [ ] Anything else?

**Comment by monoidal** [comment]
Support for linear functions was added in #447.

Support for multiplicity annotations in GADT is moved to upstream:#18378.
