### ISSUE TITLE
GHC doesn't distinguish arrow types

### ISSUE THREAD

**Issue by Tarmean** [tweag/ghc#7]
Hope this is the right place for this issue. When trying to compile

```
{-# LANGUAGE TypeFamilyDependencies #-}

data Multiplicity = One | Omega
type family FArr (p :: Multiplicity) a b = result | result -> p a b where
    FArr 'One a b = a ⊸ b
    FArr 'Omega a b = a -> b
```
GHC reports the following error:

```
LMonad.hs:28:5: error:
    • Type family equations violate injectivity annotation:
        FArr 'One a b = a ⊸ b -- Defined at LMonad.hs:28:5
        FArr 'Omega a b = a -> b -- Defined at LMonad.hs:29:5
    • In the equations for closed type family ‘FArr’
      In the type family declaration for ‘FArr’
   |
28 |     FArr 'One a b = a ⊸ b
   |     ^^^^^^^^^^^^^^^^^^^^^
```

On the other hand the following is fine:
```
{-# LANGUAGE TypeFamilyDependencies #-}

data Multiplicity = One | Omega
newtype LinFunc a b = LinFunc (a ⊸ b)
type family FArr (p :: Multiplicity) a b = result | result -> p a b where
    FArr 'One a b = LinFunc a b
    FArr 'Omega a b = a -> b
```

Similarly

```
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE FunctionalDependencies #-}
{-# LANGUAGE FlexibleInstances #-}

data Multiplicity = One | Omega
class Arr (p :: Multiplicity) a b f | f -> p a b, p a b -> f where
instance Arr 'One a b (a ⊸ b) where
instance Arr 'Omega a b (a -> b) where
```

reports

```
LMonad.hs:30:10: error:
    Functional dependencies conflict between instance declarations:
      instance Arr 'One a b (a ⊸ b) -- Defined at LMonad.hs:30:10
      instance Arr 'Omega a b (a -> b) -- Defined at LMonad.hs:31:10
   |
30 | instance Arr 'One a b (a ⊸ b) where
   |          ^^^^^^^^^^^^^^^^^^^^
```

and the following works fine:

```
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE FunctionalDependencies #-}
{-# LANGUAGE FlexibleInstances #-}

data Multiplicity = One | Omega
newtype LinFunc a b = LinFunc (a ⊸ b)
class Arr (p :: Multiplicity) a b f | f -> p a b, p a b -> f where
instance Arr 'One a b (LinFunc a b) where
instance Arr 'Omega a b (a -> b) where
```

**Comment by aspiwack** [comment]
Thanks for your report and your interest.

This bug happens is, as it happens, known. I know what causes it, but fixing it reveals other problems in the treatment of arrows in Core (and prevents base compilation). Not an easy fix. I hope to be able to address this in a few weeks.

**Comment by Tarmean** [comment]
Thanks for the response and your work, really looking forward to playing around with this!

 From what I can tell this would open up the possibilities for ugly hacks to simulate multiplicity polymorphism quite a bit. Although I guess the inference mechanism for lambdas probably would still break for something like this

    f :: Arr p a a
    f = \x -> x

**Comment by aspiwack** [comment]
This has been fixed in the `linear-types` branch by @mpickering . There was slightly more to the issue than I believed. And the fix has uncovered some other issues (which are all in the bug tracker).

Sorry that it took all this time, and thanks again for reporting.

**Comment by aspiwack** [comment]
Probably not, I've just had trouble with the Dockerfile. I'll push an appropriate image tomorrow.

**Comment by aspiwack** [comment]
As it turns out, the world isn't kind to me. I'm currently blocked on making a Docker image in [this ticket](https://ghc.haskell.org/trac/ghc/ticket/15121).

**Comment by aspiwack** [comment]
And resolved now.

@Tarmean you can now pull `tweag/linear-types:0.1.8`. If you still experience bugs there, please open tickets.

Thanks again for your patience.
