### ISSUE TITLE
Make ($) multiplicity polymorphic

### ISSUE THREAD

**Issue by aspiwack** [tweag/ghc#70]
_Depends on #60_

The typing rule for `($)` is built in the compiler. This typing rule currently uses unrestricted arrows. It should be multiplicity polymorphic.

The general type of `($)` (ignoring the levity polimorphism) is:

```haskell
($) :: (a :p-> b) ->. a :p-> b
```

The intermediate linear arrow may cause compatibility problems.

**Comment by monoidal** [comment]
Superseded by https://github.com/ghc-proposals/ghc-proposals/pull/406
