### ISSUE TITLE
Latest test failure tracking

### ISSUE THREAD

**Issue by mpickering** [tweag/ghc#82]
###  Worker Wrapper 

- [x] ATLoop
- [x] BottomFromInnerLambda
- [x] CaseBinderCPR
- [x] T10218
- [x] T10482
- [x] T10482a
- [x] T11770
- [x] T12370
- [x] T12603
- [x] T13143
- [x] T13338
- [x] T13425
- [x] T13543
- [x] T15056
- [x] T2486
- [x] T3717

- [x] T4321
- [x] T4930
- [x] T4957
- [x] T5997
- [x] T7507
- [x] T7865
- [x] T8598
- [x] T9303
- [x] UnsatFun
- [x] concprog001
- [x] debug
- [x] determ006
- [x] determ011
- [x] fact
- [x] join005
- [x] join006
- [x] simplCore.oneShot
- [x] simplrun005

- [x] strun002
### Iface lint

- [x] T11232
- [x] T3245
- [x] T4003
- [x] T5129
- [x] T7649
- [x] T7918
- [x] T7924
- [x] T9583
- [x] dynamic004
- [x] spec-inline
- [x] simplrun010
### Desugaring - Looks like something to do with unlifted types
- [x] T12622
- [x] T12689a
- [x] T13750 
- [x] T14290
- [x] T14650
- [x] T3736
- [x] T3972
- [x] T5603
- [x] T5453
- [x] T8221
- [x] T8425
- [x] bkprun09
- [x] cg005
- [x] determ008
- [x] hClose002
- [x] hClose003
- [x] hDuplicateTo001
- [x] spec001
- [x] T4306
### Core Lint - Zip Equal
- [x] T12757

- [x] T12944 - #78 

### Simplifier
- [ ] T3591
- [x] determ017
- [x] drvrun008
- [x] galois_raytrace
- [x] T4945

- [x] hpc_raytrace
- [x] T5366

- [x] joao-circular
- [x] unboxedsums12
### PrepareRHS variable
- [x] cholewo-eval

### Core Prep
- [x] ds046

```
TEST="ATLoop BottomFromInnerLambda CaseBinderCPR T10218 T10482 T10482a T11232 T11770 T12370 T12603 T12622 T12689a T12757 T12944 T13143 T13338 T13425 T13543 T13750 T14290 T14650 T15056 T2486 T3245 T3591 T3717 T3736 T3972 T4003 T4306 T4321 T4930 T4945 T4957 T5129 T5366 T5453 T5603 T5997 T7507 T7649 T7865 T7918 T7924 T8221 T8425 T8598 T9303 T9583 UnsatFun bkprun09 cg005 cholewo-eval concprog001 debug determ006 determ008 determ011 determ017 drvrun008 ds046 dynamic004 fact galois_raytrace hClose002 hClose003 hDuplicateTo001 hpc_raytrace joao-circular join005 join006 simplCore.oneShot simplrun005 simplrun010 spec-inline spec001 strun002 unboxedsums12"
```

**Comment by mpickering** [comment]
The unchecked boxes have failures in the simplifier which haven't been diagnosed.

**Comment by aspiwack** [comment]
I'm not sure that all of that has been cleared. But everything has been reclassified since. So let's close.
