### ISSUE TITLE
Two test failing on CI but not locally

### ISSUE THREAD

**Issue by mpickering** [tweag/ghc#85]
There are two tests which fail on CI but not locally.

For example, see [this builld](https://circleci.com/gh/tweag/ghc/1016). `scc002` and `T3001-2` fail but I can't reproduce this locally. This could be
an environmental difference or a difference in the settings I used to build GHC.

It should be possible debug further using the "Rerun build with SSH" option on CircleCI but I want to punt for now as are likely issues which will be showed by other tests.

**Comment by monoidal** [comment]
Tests are no longer skipped.
