### ISSUE TITLE
Notation for multiplicities

### ISSUE THREAD

**Issue by jeltsch** [tweag/ghc#9]
I think that the current notation for multiplicities is inconsistent. The multiplicity `1` means that the respective value must be used *exactly* one time, while the multiplicity `ω` means that the respective value can be used *up to* ω times (it is used exactly ω times if it appears in a circular data structure, and less than ω times otherwise).

Furthermore, `1` is already an integer literal, which can occur at the type level these days; so using it for another type-level entity could lead to ambiguities and confusion.

Finally, `ω` uses Unicode and should thus have an ASCII equivalent, but it is completely unclear (at least to me) what such an ASCII equivalent could be.

I propose to denote multiplicities by symbols that do not refer to numbers (like `1` and `ω`), but somehow convey the meanings “exactly once” and “arbitrarily often”.

**Comment by jeltsch** [comment]
Regarding the things said in the first paragraph above, I think that even the term “multiplicity” is wrong. According to the actual meaning of the word “multiplicity” (as I understand it), a multiplicity is the number of times a particular value is used, not the number of times it *may* be used. The latter is a multiplicity constraint.

**Comment by aspiwack** [comment]
Well, if we want to dig into precise semantics, ω is an ordinal number, not a cardinal number, it cannot represent the number of occurrences of something. When one uses ω as a size, the meaning is generally "any finite size". So I think it fits pretty nice.

I don't have a strong opinion on how the multiplicities should be written. But `1` and `0` are standard notations for the neutral elements of a semi-ring, hence are fairly appropriate. Though, indeed, it's probably not parsable. So either we have distinct notations for multiplicity symbols (a lexical convention could be good, like starting each multiplicity with a special symbol, such as `:`, so that multiplicities would be `:0`, `:1`, and `:ω`) or a dedicated delimiter for multiplicity expressions.

I will refrain from using phrases such as "multiplicity constraint". It is quite verbose and does not make things any clearer.

**Comment by jeltsch** [comment]
> When one uses ω as a size, the meaning is generally “any finite size”.

Really? Maybe some people use it in this sense nowadays, because they do not know what an ordinal number is and mix “any finite size” with “infinite size”. However, I learned that the symbol for “any finite size” is the star (\*). The standard notation for the set of all finite words over an alphabet Σ is Σ<sup>*</sup>. On the other hand, Σ<sup>ω</sup> is the standard notation for the set of all _infinite_ words over Σ.

**Comment by jeltsch** [comment]
> So either we have distinct notations for multiplicity symbols (a lexical convention could be good, like starting each multiplicity with a special symbol, such as `:`, so that multiplicities would be `:0`, `:1`, and `:ω`) or a dedicated delimiter for multiplicity expressions.

A lexical rule that distinguishes multiplicity symbols from everything else might be a very good thing. It would allow for a much simpler type annotation syntax. We could just write something like `x :: :1 a` and it would be clear that `:1` is not the type, since that lexical rule says it is a multiplicity. I would just advice against using `:`, since it is already used as the first character of data constructor operators and is the symbol used in `::`, which precedes multiplicities in type annotations.

**Comment by Tarmean** [comment]
I think in this context ω can be read as natural numbers.

**Comment by jeltsch** [comment]
> Maybe some people use it [the ω-symbol] in this sense nowadays, because they do not know what an ordinal number is and mix “any finite size” with “infinite size”.

@aspiwack: Just to make this clear: I did not want to say, that _you_ would not know what an ordinal number is or would mix “any finite size” with “infinite size”. What I wanted to say is that people in certain communities have encountered the ω in certain contexts (for example, infinite words) without knowing where it comes from (set theory) and what its actual meaning is (the smallest transfinite ordinal number). These people might have developed a sloppy idea of what ω means, which might have lead to a usage of ω that is not in line with its actual meaning anymore.

**Comment by jeltsch** [comment]
> I think in this context ω can be read as natural numbers.

Yes, according to the von-Neumann definition of ordinal numbers, ω is the set of natural numbers. However, 1 is the set {0} and 0 is the empty set then; so 1 would mean that only multiplicity 0 is allowed, and 0 would mean that no multiplicity is allowed. Again, using 0, 1, and ω the way they are currently used would be inconsistent.

**Comment by jeltsch** [comment]
@aspiwack:

> I will refrain from using phrases such as “multiplicity constraint”. It is quite verbose and does not make things any clearer.

At least, we should acknowledge that we are dealing with two concepts: first, usage counts, like 0 (not used), 1 (used exactly once), and 2 (used twice); second, sets of possible usage counts, like {0} (not used), {1} (used exactly once), {0, 1} (used at most once), and ℕ ∈ {ℵ₀} (used arbitrarily, including infinitely, often). I think it is crucial to not confuse these two concepts. Therefore, it would be good to have two clearly defined terms for these two different concepts.

**Comment by aspiwack** [comment]
Closing: the discussion should now move to ghc-proposals/ghc-proposals#91.
