### ISSUE TITLE
Implement the decided upon syntax for multiplicity on arrows

### ISSUE THREAD

**Issue by mpickering** [tweag/ghc#94]
The current syntax for polymorphism is the very catchy: `forall a . a -->. (One) a` as it was easy to parse. This will need to be changed.

**Comment by monoidal** [comment]
This includes at least: parsing, pretty-printing (currently uses `->@[p]`), debugging output in TcEvidence (left as TODO at #201)

**Comment by aspiwack** [comment]
Though, since the precise syntax hasn't been agreed on, we can fix after the diff is submitted, as long as there is an entry for all of them.

**Comment by monoidal** [comment]
After we have the decision on syntax, we need to make sure the implementation does not steal it from valid H98 programs. Currently, ghc-8.6 with `-XTypeOperators` accepts `type a ->. b = Int`, while the linear-types branch rejects this code. Of course, if the decided syntax won't conflict with currently valid identifiers, there will be nothing to do.

**Comment by monoidal** [comment]
This is now unblocked.

**Comment by mboes** [comment]
@aspiwack proposes: let's just remove this stand-in syntax for multiplicity polymorphism.

**Comment by mboes** [comment]
To be clear, not a long term solution, but the point is - getting the syntax right for this shouldn't be a blocker.

**Comment by monoidal** [comment]
The stand-in syntax was removed. No longer a blocker.

**Comment by aspiwack** [comment]
Moved to upstream:#18459 .
