### ISSUE TITLE
Reenable a disabled assertion to do with levels

### ISSUE THREAD

**Issue by mpickering** [tweag/ghc#97]
There is an assertion which I disabled in 7356f506c0a4b43808009d900354bd4e7f078401

I couldn't understand the errors but they were to do with type variables being of different levels and escaping some kind of scope. It seems to come up with higher-order code which mentions data constructors. 

I first ran into an assertion failure when compiling `Data.OldList`. To fix that, I added a type signature. 

d63c66ffa1c57c486a8ffe757c78cf4d19055d0c

It also happened when compiling DynFlags.hs. That's when I disabled the assertion.

**Comment by aspiwack** [comment]
The assertion was reenabled by c930f9f . But part of the OldList module wasn't reverted.
